### ISSUE TITLE
sjs command supports only absolute paths (on OSX, with master branch)

### ISSUE THREAD

**Issue by gkovacs** [sweet-js/sweet.js#648]
To reproduce:

Create a file test3.js in your home directory

Observe that `sjs test3.js` or `sjs ./test3.js` doesn't run, instead outputting the error:

```
/usr/local/lib/node_modules/sweet.js/node_modules/resolve/lib/sync.js:39
    throw err;
    ^

Error: Cannot find module './test3.js' from '/usr/local/lib/node_modules/sweet.js/'
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/sweet.js/node_modules/resolve/lib/sync.js:37:15)
    at NodeLoader.normalize (/usr/local/lib/node_modules/sweet.js/dist/node-loader.js:40:44)
    at NodeLoader.compile (/usr/local/lib/node_modules/sweet.js/dist/sweet-loader.js:146:21)
    at compileModule (/usr/local/lib/node_modules/sweet.js/dist/sweet.js:12:17)
    at compile (/usr/local/lib/node_modules/sweet.js/dist/sweet.js:30:14)
    at /usr/local/lib/node_modules/sweet.js/bin/sjs:32:16
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sweet.js/bin/sjs:31:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
```

But providing an absolute path, ie `sjs /Users/geza/test3.js` fixes the issue.

I think this is easily fixable, and will provide a pull request soon

**Comment by gabejohnson** [comment]
@disnet, someone just asked about this in the Gitter room.
